# Generated by Django 4.2.3 on 2024-02-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_enrollment_knowledge_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(0, 'Admin'), (1, 'Teacher'), (2, 'Student')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
