# Generated by Django 4.2.3 on 2024-02-28 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='parent_phone_number',
        ),
    ]
