# Generated by Django 4.2.3 on 2024-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_user_parent_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='knowledge_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('intermediate', 'Intermediate'), ('upper intermediate', 'Upper Intermediate')], max_length=255),
        ),
    ]
