# Generated by Django 4.2.3 on 2024-03-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_enrollment_knowledge_level_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_user_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
