version: '3.8'

services:
  web:
      build: 
        context: ./src
        dockerfile: Dockerfile.local
      command: python manage.py runserver 0.0.0.0:8000 --settings=core.settings.base
      volumes:
        - ./src/:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - .env
      depends_on:
        - db
  db:
    image: postgres:12-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
  

volumes:
  postgres_data:
  static_volume:
  media_volume:
