services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12-bookworm
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
  static_volume:
  media_volume:
