version: '3.7'

services:
  web:
      build: .
      volumes:
        - ./:/usr/src/app/
      ports:
        - 8000:8000
      env_file:
        - .env
      depends_on:
        - db
  db:
    image: postgres:12-bookworm
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
  media_volume:
