# Generated by Django 4.2.3 on 2024-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='info',
            field=models.TextField(default='course info'),
            preserve_default=False,
        ),
    ]
