# Generated by Django 4.2.3 on 2024-04-21 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_examgrade_grades_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(related_name='course_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
