# Generated by Django 4.2.3 on 2024-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_email_alter_user_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='knowledge_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Elementary', 'Elementary'), ('Intermediate', 'Intermediate'), ('Upper Intermediate', 'Upper Intermediate')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Student', 'Student')], max_length=15),
        ),
    ]
